### ISSUE TITLE
How to use the trained model for inference?

### ISSUE THREAD

**Issue by smith-co** [elcaiseri/Siamese-Network#2]
I see you trained the model with:

```
siamese_model.fit(train_dataset, epochs=10, validation_data=val_dataset)
```

But I don't understand how to apply the model to new data. Also the similarity between positive and negative is so so close!

```
Positive similarity: 0.99825317
Negative similarity 0.99522734
```

Can you please provide any insight?

**Comment by elcaiseri** [comment]
First: You can infer your model by **feeding the embedding inputs to “cosine similarity”.**
Check `Inspecting what the network has learned.` section again.

Second: You are right `the similarity between positive and negative is so so close!` but at this primary level **`We should expect the similarity between the anchor and positive images to be larger than the similarity between the anchor and the negative images`.**

**Comment by smith-co** [comment]
Not quite sure what you meant for the similarity score. Suppose you are given two images, how would you even understand whether the two images are similar or not using this model? The score between positive and negative is extremely close to make the model to be useful.

Any idea how to make the make the model better?

**Comment by elcaiseri** [comment]
I have added inference stage, may it help you.

Thanks
